### ISSUE TITLE
Process DNS 'Status' values, Related to issue #7 

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/Cont3xt#10]
Process the 'Status' response value for the very first A record response and if 'Status' != '0', do not process any of the other type DNS requests for the indicator. The most common error type will be '3' : "Non-Existent Domain".

Display the "description" value in RED bold text (inside a bubble) per Status code as found in the following array, and place under the iType bubble as you would the first A record response. 

  var errors = [
    { "name": "NoError", "description": "No Error"}, // 0
    { "name": "FormErr", "description": "Format Error"}, // 1
    { "name": "ServFail", "description": "Server Failure"}, // 2
    { "name": "NXDomain", "description": "Non-Existent Domain"}, // 3
    { "name": "NotImp", "description": "Not Implemented"}, // 4
    { "name": "Refused", "description": "Query Refused"}, // 5
    { "name": "YXDomain", "description": "Name Exists when it should not"}, // 6
    { "name": "YXRRSet", "description": "RR Set Exists when it should not"}, // 7
    { "name": "NXRRSet", "description": "RR Set that should exist does not"}, // 8
    { "name": "NotAuth", "description": "Not Authorized"} // 9
  ];

**Comment by TobySalusky** [comment]
In ResultsDNS.js, I added a dictionary containing the values from which error status elements are created

**Comment by WilliamSalusky** [comment]
Please reopen this issue. When NDS error conditions are encountered, they should be displayed in a result box. Read the issue again.
