### ISSUE TITLE
Shodan tooltip report presentation

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/cont3xt#101]
For Shodan results, add two tooltip report sections that will display tables after tags and ports.

title: "Service/Port info for ${indicator}"
product
port
title ;# limit 12 chars, tooltip the rest
server
module
data  ;# limit 12 chars, tooltip the rest
html  ;# limit 12 chars, tooltip the rest

title: "Certificates for ${indicator}"
cert.issued
cert.expires
cert.fingerprint.sha1 ;# link back to Censys search
cert.issuer   ;# in a tooltip
cert.subject  ;# in a tooltip

**Comment by WilliamSalusky** [comment]
The report section is done, but can you present them immediately after the tags and ports section up top?

**Comment by TobySalusky** [comment]
now immediately after tags/ports
