### ISSUE TITLE
Compile error - Edit.js

### ISSUE THREAD

**Issue by LaBuse56** [TobySalusky/cont3xt#102]
Step to reproduce:
Install fresh by following README
Default kali versions:
npm -v                                                                                                                                                   
7.5.2

node -v                                                                                                                                                  
v12.22.5

Backend starts fine:
npm start                                                                                                                                                

> cont3xtbackend@0.0.0 start
> node ./bin/www

Listening on port 4000

UI doesn't compile:
Failed to compile

./src/Pages/Edit.js
Syntax error: Unexpected token (246:41)

  244 | 
  245 |         const parse = require('color-parse')
> 246 |         let initCol = parse(props.color ?? 'orange')
      |                                          ^
  247 | 
  248 |         setState({
  249 |             displayColorPicker: false,

This error occurred during the build time and cannot be dismissed.

**Comment by WilliamSalusky** [comment]
I have seen this very error with an install attempt that failed to install deps. Delete that git clone, grab it again and try to eyeball for any failures during the `npm ci install`

I'm also not certain if that older node version is involved. I'll have to grab a Kali image, and check it out myself.

If a second `npm ci install` on a fresh git clone also fails... dump it again, and just go with a generic `npm install`

**Comment by WilliamSalusky** [comment]
Hey @LaBuse56, I tried it out on Kali and it gets up and running, no need to update node either. I suspect your issue was also a failed npm install. I hope the fresh clone and `npm ci install` clears you up. Don't forget to configure your .env file. It's a pretty boring experience without any integrations.

**Comment by LaBuse56** [comment]
I agree.. Looks like my setup had a glitch... Still having issues but definitively on my side!
