### ISSUE TITLE
DNS over HTTPS enhancement - Add CAA and SOA records - related to issue #7

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/Cont3xt#12]
CAA responses are going to be fun. See below for pointers on handling the decode.

curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=yahoo.com&type=CAA'
curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=yahoo.com&type=SOA'

For CAA, using this example data response:
      "data": "\\# 21 00 05 69 73 73 75 65 67 6c 6f 62 61 6c 73 69 67 6e 2e 63 6f 6d"
which decodes to "issue globalsign.com"

From the above example: The decimal number '21' identifies how many following hex byte pairs to expect. The next two hex byte pairs '\x00 05' identifies the number of hex bytes to decode into the first word where '\x69 73 73 75 65' decodes to ascii as 'issue'. The remaining hex bytes '\x67 6c 6f 62 61 6c 73 69 67 6e 2e 63 6f 6d' decode to ascii as 'globalsign.com'.

So the CAA bubble in this case would contain "issue globalsign.com"

For SOA, Just display the returned text in an SOA bubble.

**Comment by TobySalusky** [comment]
Added the types to the DNS data dictionary, converting CAA hex into readable text
