### ISSUE TITLE
Generate link back to the Cont3xt app to review sub indicators (in new tab) -- FUTURE

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/cont3xt#24]
For all sub resultbox indicators, generate a link back to the Cont3xt app to review and resulting sub indicators from DNS queries, etc...

For instance... When a domain is resolved and IP's are displayed for A records, etc.. display an 'external-link' icon that is a clickable link that will be displayed immediately after the IP address that links back to ${site}/?q=${indicator}

Use this icon: 
https://feathericons.com/?query=external-link

**Comment by TobySalusky** [comment]
Added an external link icon that takes you to the context site for the specified input on dns and asn sub-results
