### ISSUE TITLE
Split url arrays out from frame js

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/Cont3xt#3]
Please split out the Type based genLinks url arrays into separate config js files so that your top level application changes do not require manual intervention by individuals who will have to re-add custom cSite url configurations. FYI, cSite == Context site. 

Soon enough it will be time to choose a data store. We'll need to be able to manage user preferences. And per user custom url configurations.

**Comment by TobySalusky** [comment]
I made a Configurations.js file that stores how each of the three tabs are generated, while combining the GeneralHunting, InternalTools, and EnterpriseLinks scripts into LinkTab.js, which is then passed a configuration from Configurations.js

**Comment by TobySalusky** [comment]
Update: The URL arrays are no longer located in a javascript file, the configurations are now loaded from text files in the config folder. This should make it easier for when user-specified links are added to the website, since they can be storable in this form.
