### ISSUE TITLE
Add query string support to search a base64 encoded indicator

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/cont3xt#33]
Evaluate the query string and if a new key name of 'b' is present, first base64 decode that value and then treat it as though it were passed as the 'q' value.

Where:
http://127.0.0.1:3000/?b=eWFob28uY29t

Would be the same as:
http://127.0.0.1:3000/?q=yahoo.com

**Comment by TobySalusky** [comment]
This has been added
