### ISSUE TITLE
URLScan tooltip report presentation

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/cont3xt#53]
Generate a table for the `results` section 

Columns should be:
task.visibility, task.method, task.url, page.country, page.server, page.status, task.uuid, page.screenshot, task.time

Limit the maxlength of `task.uuid` to 15, and give it an external link that pops out to https://urlscan.io/result/${task.uuid}

Also limit the maxlength of `page.screenshot` and give it a hover over display of the rendered screenshot

Default the time sort to descending, most recently seen first

**Comment by TobySalusky** [comment]
Added a table for this result infobox

**Comment by WilliamSalusky** [comment]
Need to add the URLScan table output to the Report generation/export
