### ISSUE TITLE
Color picker not saving the chosen color for newly configured links

### ISSUE THREAD

**Issue by WilliamSalusky** [TobySalusky/Cont3xt#8]
I really like what you've done with the configuration editor. The editor however does not save the color chosen in the picker.

Also, I highly recommend using a SAVE button so that it is understood that you are about to save changes instead of just using the back button. Don't get rid of the back button from the config editor, but it shouldn't be responsible for saving App config changes.

**Comment by WilliamSalusky** [comment]
In hindsight, it looks like you are actively working on this section. Sorry

**Comment by TobySalusky** [comment]
Added colour attribute to data table and file entries
